export const data = [
  {
    _id: "63b43907a8a24c34209062f1",
    ofYear: "first",
    subjects: {
      all: "All",
      engineering_chemistry: "Engineering Chemistry",
      mathematics_I: "Mathematics-I",
      english_for_communication: "English For Communication",
      engineering_electronics: "Basic Electrical & Electronics Engineering",
      engineering_graphics: "Engineering Graphics",
      engineering_physics: "Engineering Physics",
      mathematics_II: "Mathematics-II",
      engineering_mechanical: "Basic Mechanical Engineering",
      engineering_civil: "Basic Civil Engineering & Mechanics",
      engineering_computer: "Basic Computer Engineering",
    },
    branches: ["IT", "CS", "civil", "EC", "mechanical"],
  },
  {
    _id: "63b43907a8a24c34209062f1",
    ofYear: "second",
    subjects: {
      all: "All",
      engineering_environment: "Energy & Environmental Engineering",
      discrete_structure: "Mathematics-I",
      data_structure: "Data Structure",
      object_oriented_programming: "Object Oriented Programming",
      digital_system: "Digital Circuits & System",
    },
    branches: ["IT", "CS"],
  },
  {
    _id: "63b43907a8a24c34209062f1",
    ofYear: "second",
    subjects: {
      all: "All",
      mathematics_III: "Mathematics-III",
      construction_materials: "Construction Materials",
      surveying: "Surveying",
      building_planning_architecture: "Building Planning & Architecture",
      strength_of_materials: "Strength of Materials",
    },
    branches: ["civil"],
  },
];
