export const data = [
  {
    id: 1,
    filename: "Data structure - unit 01",
    category: "notes",
    author: "Aaryan Patel",
    likes: 3,
    time: "5 days ago",
  },
  {
    id: 2,
    filename: "Data structure - unit 02",
    category: "notes",
    author: "Aaryan Patel",
    likes: 5,
    time: "4 days ago",
  },
  {
    id: 1,
    filename: "Object oriented programming - unit 04",
    category: "assignment",
    author: "Nikky Patel",
    likes: 1,
    time: "2 days ago",
  },
  {
    id: 1,
    filename: "Digital System - unit 02",
    category: "practical",
    author: "Rahul Mishra",
    likes: 13,
    time: "10 days ago",
  },
  {
    id: 1,
    filename: "Object oriented programming - unit 04",
    category: "notes",
    author: "Nikky Patel",
    likes: 1,
    time: "2 days ago",
  },
  {
    id: 1,
    filename: "Digital System - unit 02",
    category: "assignment",
    author: "Rahul Mishra",
    likes: 13,
    time: "10 days ago",
  },
];
